// <auto-generated />
using System;
using ApFpoly_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApFpoly_API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApFpoly_API.Model.BangDiem", b =>
                {
                    b.Property<string>("MaBangDiem")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<double>("Diem")
                        .HasColumnType("float");

                    b.Property<string>("MaGiangVien")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaMonHoc")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaBangDiem");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaMonHoc");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("BangDiem");
                });

            modelBuilder.Entity("ApFpoly_API.Model.DiemDanh", b =>
                {
                    b.Property<string>("MaDiemDanh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("CoMat")
                        .HasColumnType("bit");

                    b.Property<string>("MaGiangVien")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaLichHoc")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaMonHoc")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaDiemDanh");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaLichHoc");

                    b.HasIndex("MaMonHoc");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("DiemDanh");
                });

            modelBuilder.Entity("ApFpoly_API.Model.GiangVien", b =>
                {
                    b.Property<string>("MaGiangVien")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("AnhGiangVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DanToc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Nganh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenGiangVien")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaGiangVien");

                    b.ToTable("GiangVien");

                    b.HasData(
                        new
                        {
                            MaGiangVien = "GV001",
                            AnhGiangVien = "Image_PK0002.jpeg",
                            CCCD = "123456789",
                            ChucVu = "Giảng viên",
                            DanToc = "Kinh",
                            DiaChi = "123 Đường ABC, Quận XYZ, TP HCM",
                            Email = "nguyenvana@giangvien.com",
                            GioiTinh = "Nam",
                            Nganh = "Công nghệ thông tin",
                            NgaySinh = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(819),
                            NgayVaoLam = new DateTime(2010, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456789",
                            TenGiangVien = "Nguyễn Văn A",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaGiangVien = "GV002",
                            AnhGiangVien = "Image_PK0002.jpeg",
                            CCCD = "987654321",
                            ChucVu = "Phó trưởng khoa",
                            DanToc = "Kinh",
                            DiaChi = "456 Đường XYZ, Quận ABC, TP HCM",
                            Email = "tranthib@giangvien.com",
                            GioiTinh = "Nữ",
                            Nganh = "Kỹ thuật điện tử",
                            NgaySinh = new DateTime(1975, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(825),
                            NgayVaoLam = new DateTime(2008, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0987654321",
                            TenGiangVien = "Trần Thị B",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaGiangVien = "GV003",
                            AnhGiangVien = "Image_PK0002.jpeg",
                            CCCD = "987654321",
                            ChucVu = "Trưởng khoa",
                            DanToc = "Kinh",
                            DiaChi = "789 Đường XYZ, Quận XYZ, TP HCM",
                            Email = "phamthic@giangvien.com",
                            GioiTinh = "Nữ",
                            Nganh = "Quản trị kinh doanh",
                            NgaySinh = new DateTime(1985, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(828),
                            NgayVaoLam = new DateTime(2012, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456789",
                            TenGiangVien = "Phạm Thị C",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaGiangVien = "GV004",
                            AnhGiangVien = "Image_PK0002.jpeg",
                            CCCD = "123456789",
                            ChucVu = "Phó trưởng khoa",
                            DanToc = "Kinh",
                            DiaChi = "101 Đường ABC, Quận ABC, TP HCM",
                            Email = "levand@giangvien.com",
                            GioiTinh = "Nam",
                            Nganh = "Kỹ thuật xây dựng",
                            NgaySinh = new DateTime(1978, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(832),
                            NgayVaoLam = new DateTime(2011, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0987654321",
                            TenGiangVien = "Lê Văn D",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaGiangVien = "GV005",
                            AnhGiangVien = "Image_PK0002.jpeg",
                            CCCD = "987654321",
                            ChucVu = "Giảng viên",
                            DanToc = "Kinh",
                            DiaChi = "456 Đường XYZ, Quận XYZ, TP HCM",
                            Email = "hoangthie@giangvien.com",
                            GioiTinh = "Nữ",
                            Nganh = "Ngôn ngữ Anh",
                            NgaySinh = new DateTime(1982, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(835),
                            NgayVaoLam = new DateTime(2015, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456789",
                            TenGiangVien = "Hoàng Thị E",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaGiangVien = "GV006",
                            AnhGiangVien = "Image_PK0002.jpeg",
                            CCCD = "123456789",
                            ChucVu = "Trưởng khoa",
                            DanToc = "Kinh",
                            DiaChi = "789 Đường ABC, Quận ABC, TP HCM",
                            Email = "dangvanf@giangvien.com",
                            GioiTinh = "Nam",
                            Nganh = "Kinh tế",
                            NgaySinh = new DateTime(1970, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(838),
                            NgayVaoLam = new DateTime(2005, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0987654321",
                            TenGiangVien = "Đặng Văn F",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaGiangVien = "GV007",
                            AnhGiangVien = "Image_PK0002.jpeg",
                            CCCD = "987654321",
                            ChucVu = "Giảng viên",
                            DanToc = "Kinh",
                            DiaChi = "101 Đường XYZ, Quận ABC, Quận XYZ, TP HCM",
                            Email = "vuthig@giangvien.com",
                            GioiTinh = "Nữ",
                            Nganh = "Mỹ thuật",
                            NgaySinh = new DateTime(1973, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(841),
                            NgayVaoLam = new DateTime(2013, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456789",
                            TenGiangVien = "Vũ Thị G",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaGiangVien = "GV008",
                            AnhGiangVien = "Image_PK0002.jpeg",
                            CCCD = "123456789",
                            ChucVu = "Phó trưởng khoa",
                            DanToc = "Kinh",
                            DiaChi = "123 Đường ABC, Quận ABC, TP HCM",
                            Email = "nguyenthanhh@giangvien.com",
                            GioiTinh = "Nam",
                            Nganh = "Tài chính",
                            NgaySinh = new DateTime(1976, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(844),
                            NgayVaoLam = new DateTime(2012, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0987654321",
                            TenGiangVien = "Nguyễn Thanh H",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaGiangVien = "GV009",
                            AnhGiangVien = "Image_PK0002.jpeg",
                            CCCD = "987654321",
                            ChucVu = "Giảng viên",
                            DanToc = "Kinh",
                            DiaChi = "456 Đường XYZ, Quận XYZ, TP HCM",
                            Email = "tranvani@giangvien.com",
                            GioiTinh = "Nam",
                            Nganh = "Luật",
                            NgaySinh = new DateTime(1983, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(847),
                            NgayVaoLam = new DateTime(2010, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456789",
                            TenGiangVien = "Trần Văn I",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaGiangVien = "GV010",
                            AnhGiangVien = "Image_PK0002.jpeg",
                            CCCD = "123456789",
                            ChucVu = "Trưởng khoa",
                            DanToc = "Kinh",
                            DiaChi = "101 Đường ABC, Quận ABC, TP HCM",
                            Email = "lethik@giangvien.com",
                            GioiTinh = "Nữ",
                            Nganh = "Khoa học máy tính",
                            NgaySinh = new DateTime(1979, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(850),
                            NgayVaoLam = new DateTime(2013, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0987654321",
                            TenGiangVien = "Lê Thị K",
                            TinhTrang = "Đang hoạt động"
                        });
                });

            modelBuilder.Entity("ApFpoly_API.Model.HocKyBlock", b =>
                {
                    b.Property<string>("MaHocKyBlock")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBlock")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaHocKyBlock");

                    b.ToTable("HocKyBlock");

                    b.HasData(
                        new
                        {
                            MaHocKyBlock = "SP24BL1",
                            NgayBatDau = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenBlock = "Block 1",
                            TenHocKy = "Spring 2024",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaHocKyBlock = "SP24BL2",
                            NgayBatDau = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenBlock = "Block 2",
                            TenHocKy = "Spring 2024",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaHocKyBlock = "SM24BL1",
                            NgayBatDau = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenBlock = "Block 1",
                            TenHocKy = "Summer 2024",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaHocKyBlock = "SM24BL2",
                            NgayBatDau = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2024, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenBlock = "Block 2",
                            TenHocKy = "Summer 2024",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaHocKyBlock = "FA24BL1",
                            NgayBatDau = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2024, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenBlock = "Block 1",
                            TenHocKy = "Fall 2024",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaHocKyBlock = "FA24BL2",
                            NgayBatDau = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenBlock = "Block 2",
                            TenHocKy = "Fall 2024",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaHocKyBlock = "SP25BL1",
                            NgayBatDau = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenBlock = "Block 1",
                            TenHocKy = "Spring 2025",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaHocKyBlock = "SP25BL2",
                            NgayBatDau = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenBlock = "Block 2",
                            TenHocKy = "Spring 2025",
                            TinhTrang = "Đang hoạt động"
                        });
                });

            modelBuilder.Entity("ApFpoly_API.Model.LichHoc", b =>
                {
                    b.Property<string>("MaLichHoc")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaGiangVien")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaHocKyBlock")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaMonHoc")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaLichHoc");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaHocKyBlock");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaMonHoc");

                    b.HasIndex("MaPhong");

                    b.ToTable("LichHoc");
                });

            modelBuilder.Entity("ApFpoly_API.Model.LopHoc", b =>
                {
                    b.Property<string>("MaLop")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<short>("SucChua")
                        .HasColumnType("smallint");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaLop");

                    b.ToTable("LopHoc");

                    b.HasData(
                        new
                        {
                            MaLop = "LH001",
                            NgayTao = new DateTime(2024, 2, 26, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(381),
                            SucChua = (short)30,
                            TenLop = "Toán cao cấp",
                            TinhTrang = "Đang Đang hoạt động"
                        },
                        new
                        {
                            MaLop = "LH002",
                            NgayTao = new DateTime(2024, 3, 7, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(399),
                            SucChua = (short)25,
                            TenLop = "Vật lý đại cương",
                            TinhTrang = "Đang Đang hoạt động"
                        },
                        new
                        {
                            MaLop = "LH003",
                            NgayTao = new DateTime(2024, 3, 17, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(402),
                            SucChua = (short)20,
                            TenLop = "Hóa học cơ bản",
                            TinhTrang = "Đang Đang hoạt động"
                        },
                        new
                        {
                            MaLop = "LH004",
                            NgayTao = new DateTime(2024, 3, 27, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(403),
                            SucChua = (short)35,
                            TenLop = "Lập trình C#",
                            TinhTrang = "Đang Đang hoạt động"
                        },
                        new
                        {
                            MaLop = "LH005",
                            NgayTao = new DateTime(2024, 4, 6, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(405),
                            SucChua = (short)30,
                            TenLop = "Lập trình Java",
                            TinhTrang = "Đang Đang hoạt động"
                        },
                        new
                        {
                            MaLop = "LH006",
                            NgayTao = new DateTime(2024, 4, 16, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(407),
                            SucChua = (short)25,
                            TenLop = "Lập trình Python",
                            TinhTrang = "Đang Đang hoạt động"
                        },
                        new
                        {
                            MaLop = "LH007",
                            NgayTao = new DateTime(2024, 4, 26, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(408),
                            SucChua = (short)20,
                            TenLop = "Lập trình JavaScript",
                            TinhTrang = "Đang Đang hoạt động"
                        },
                        new
                        {
                            MaLop = "LH008",
                            NgayTao = new DateTime(2024, 5, 6, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(410),
                            SucChua = (short)35,
                            TenLop = "Lập trình PHP",
                            TinhTrang = "Đang Đang hoạt động"
                        },
                        new
                        {
                            MaLop = "LH009",
                            NgayTao = new DateTime(2024, 5, 16, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(411),
                            SucChua = (short)30,
                            TenLop = "Lập trình Ruby",
                            TinhTrang = "Đang Đang hoạt động"
                        },
                        new
                        {
                            MaLop = "LH010",
                            NgayTao = new DateTime(2024, 5, 26, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(412),
                            SucChua = (short)25,
                            TenLop = "Lập trình Swift",
                            TinhTrang = "Đang Đang hoạt động"
                        });
                });

            modelBuilder.Entity("ApFpoly_API.Model.LopHocChiTiet", b =>
                {
                    b.Property<string>("MaLopHocChiTiet")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaLopHocChiTiet");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("LopHocChiTiet");
                });

            modelBuilder.Entity("ApFpoly_API.Model.MonHoc", b =>
                {
                    b.Property<string>("MaMonHoc")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungMonHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("SoBuoi")
                        .HasColumnType("smallint");

                    b.Property<string>("TaiLieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<short?>("TinChi")
                        .HasColumnType("smallint");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaMonHoc");

                    b.ToTable("MonHoc");

                    b.HasData(
                        new
                        {
                            MaMonHoc = "MH001",
                            NgayTao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDungMonHoc = "Toán cao cấp dành cho sinh viên ngành kỹ thuật.",
                            SoBuoi = (short)5,
                            TaiLieu = "Giáo trình Toán Cao Cấp - Tập 1",
                            TenMonHoc = "Toán Cao Cấp",
                            TinChi = (short)3,
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaMonHoc = "MH002",
                            NgayTao = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDungMonHoc = "Kiến thức cơ bản về vật lý cho sinh viên.",
                            SoBuoi = (short)4,
                            TaiLieu = "Giáo trình Vật Lý Đại Cương",
                            TenMonHoc = "Vật Lý Đại Cương",
                            TinChi = (short)4,
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaMonHoc = "MH003",
                            NgayTao = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDungMonHoc = "Kiến thức hóa học cơ bản cho sinh viên không chuyên.",
                            SoBuoi = (short)5,
                            TaiLieu = "Giáo trình Hóa Học Cơ Bản",
                            TenMonHoc = "Hóa Học Cơ Bản",
                            TinChi = (short)3,
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaMonHoc = "MH004",
                            NgayTao = new DateTime(2023, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDungMonHoc = "Giới thiệu về lập trình C.",
                            SoBuoi = (short)4,
                            TaiLieu = "Giáo trình Lập Trình C",
                            TenMonHoc = "Lập Trình C",
                            TinChi = (short)3,
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaMonHoc = "MH005",
                            NgayTao = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDungMonHoc = "Kiến thức cơ bản về cơ sở dữ liệu.",
                            SoBuoi = (short)6,
                            TaiLieu = "Giáo trình Cơ Sở Dữ Liệu",
                            TenMonHoc = "Cơ Sở Dữ Liệu",
                            TinChi = (short)4,
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaMonHoc = "MH006",
                            NgayTao = new DateTime(2023, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDungMonHoc = "Giới thiệu về hệ điều hành và các khái niệm cơ bản.",
                            SoBuoi = (short)4,
                            TaiLieu = "Giáo trình Hệ Điều Hành",
                            TenMonHoc = "Hệ Điều Hành",
                            TinChi = (short)3,
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaMonHoc = "MH007",
                            NgayTao = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDungMonHoc = "Kiến thức cơ bản về mạng máy tính.",
                            SoBuoi = (short)4,
                            TaiLieu = "Giáo trình Mạng Máy Tính",
                            TenMonHoc = "Mạng Máy Tính",
                            TinChi = (short)3,
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaMonHoc = "MH008",
                            NgayTao = new DateTime(2023, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDungMonHoc = "Giới thiệu về trí tuệ nhân tạo và các ứng dụng.",
                            SoBuoi = (short)7,
                            TaiLieu = "Giáo trình Trí Tuệ Nhân Tạo",
                            TenMonHoc = "Trí Tuệ Nhân Tạo",
                            TinChi = (short)4,
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaMonHoc = "MH009",
                            NgayTao = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDungMonHoc = "Giới thiệu về phân tích và thiết kế hệ thống.",
                            SoBuoi = (short)4,
                            TaiLieu = "Giáo trình Phân Tích Thiết Kế Hệ Thống",
                            TenMonHoc = "Phân Tích Thiết Kế Hệ Thống",
                            TinChi = (short)3,
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaMonHoc = "MH010",
                            NgayTao = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDungMonHoc = "Kiến thức cơ bản về kinh tế học.",
                            SoBuoi = (short)4,
                            TaiLieu = "Giáo trình Kinh Tế Học",
                            TenMonHoc = "Kinh Tế Học",
                            TinChi = (short)3,
                            TinhTrang = "Đang hoạt động"
                        });
                });

            modelBuilder.Entity("ApFpoly_API.Model.NopBai", b =>
                {
                    b.Property<string>("MaNopBai")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaGiangVien")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaMonHoc")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucNopBai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenFileNop")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaNopBai");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaMonHoc");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("NopBai");
                });

            modelBuilder.Entity("ApFpoly_API.Model.PhongHoc", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("LoaiPhong")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<short>("SucChua")
                        .HasColumnType("smallint");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaPhong");

                    b.ToTable("PhongHoc");

                    b.HasData(
                        new
                        {
                            MaPhong = "P001",
                            LoaiPhong = "Giảng Đường",
                            NgayTao = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SucChua = (short)100,
                            TenPhong = "Phòng A1",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaPhong = "P002",
                            LoaiPhong = "Phòng Thí Nghiệm",
                            NgayTao = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SucChua = (short)30,
                            TenPhong = "Phòng B1",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaPhong = "P003",
                            LoaiPhong = "Phòng Học Nhóm",
                            NgayTao = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SucChua = (short)20,
                            TenPhong = "Phòng C1",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaPhong = "P004",
                            LoaiPhong = "Phòng Máy Tính",
                            NgayTao = new DateTime(2022, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SucChua = (short)40,
                            TenPhong = "Phòng D1",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaPhong = "P005",
                            LoaiPhong = "Phòng Thực Hành",
                            NgayTao = new DateTime(2022, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SucChua = (short)50,
                            TenPhong = "Phòng E1",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaPhong = "P006",
                            LoaiPhong = "Phòng Hội Thảo",
                            NgayTao = new DateTime(2022, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SucChua = (short)70,
                            TenPhong = "Phòng F1",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaPhong = "P007",
                            LoaiPhong = "Giảng Đường",
                            NgayTao = new DateTime(2022, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SucChua = (short)100,
                            TenPhong = "Phòng G1",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaPhong = "P008",
                            LoaiPhong = "Phòng Thí Nghiệm",
                            NgayTao = new DateTime(2022, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SucChua = (short)30,
                            TenPhong = "Phòng H1",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaPhong = "P009",
                            LoaiPhong = "Phòng Học Nhóm",
                            NgayTao = new DateTime(2022, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SucChua = (short)20,
                            TenPhong = "Phòng I1",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            MaPhong = "P010",
                            LoaiPhong = "Phòng Máy Tính",
                            NgayTao = new DateTime(2022, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SucChua = (short)40,
                            TenPhong = "Phòng J1",
                            TinhTrang = "Đang hoạt động"
                        });
                });

            modelBuilder.Entity("ApFpoly_API.Model.SinhVien", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("AnhSinhVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ChuyenNganh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DanToc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Khoa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayNhapHoc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenSinhVien")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaSinhVien");

                    b.ToTable("SinhVien");

                    b.HasData(
                        new
                        {
                            MaSinhVien = "SV001",
                            AnhSinhVien = "pexels-justin-shaifer-501272-1222271.jpg",
                            CCCD = "123456789012",
                            ChuyenNganh = "Khoa Học Máy Tính",
                            DanToc = "Kinh",
                            DiaChi = "123 Đường A, Quận 1, TP.HCM",
                            Email = "nguyenvana@sinhvien.com",
                            GioiTinh = "Nam",
                            Khoa = "CNTT",
                            NgayNhapHoc = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(2000, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(565),
                            SoDienThoai = "0901234567",
                            TenSinhVien = "Nguyễn Văn A",
                            TinhTrang = "Đang học"
                        },
                        new
                        {
                            MaSinhVien = "SV002",
                            AnhSinhVien = "Image_PK0002.jpeg",
                            CCCD = "234567890123",
                            ChuyenNganh = "Quản Trị Kinh Doanh",
                            DanToc = "Kinh",
                            DiaChi = "456 Đường B, Quận 2, TP.HCM",
                            Email = "tranthib@sinhvien.com",
                            GioiTinh = "Nữ",
                            Khoa = "Kinh Tế",
                            NgayNhapHoc = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(2001, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(570),
                            SoDienThoai = "0902345678",
                            TenSinhVien = "Trần Thị B",
                            TinhTrang = "Đang học"
                        },
                        new
                        {
                            MaSinhVien = "SV003",
                            AnhSinhVien = "Image_PK0002.jpeg",
                            CCCD = "345678901234",
                            ChuyenNganh = "Mạng Máy Tính",
                            DanToc = "Kinh",
                            DiaChi = "789 Đường C, Quận 3, TP.HCM",
                            Email = "levanc@sinhvien.com",
                            GioiTinh = "Nam",
                            Khoa = "CNTT",
                            NgayNhapHoc = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(2000, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(574),
                            SoDienThoai = "0903456789",
                            TenSinhVien = "Lê Văn C",
                            TinhTrang = "Đang học"
                        },
                        new
                        {
                            MaSinhVien = "SV004",
                            AnhSinhVien = "images.jpg",
                            CCCD = "456789012345",
                            ChuyenNganh = "Kế Toán",
                            DanToc = "Kinh",
                            DiaChi = "101 Đường D, Quận 4, TP.HCM",
                            Email = "phamthid@sinhvien.com",
                            GioiTinh = "Nữ",
                            Khoa = "Kinh Tế",
                            NgayNhapHoc = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(2001, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(578),
                            SoDienThoai = "0904567890",
                            TenSinhVien = "Phạm Thị D",
                            TinhTrang = "Đang học"
                        },
                        new
                        {
                            MaSinhVien = "SV005",
                            AnhSinhVien = "Image_PK0002.jpeg",
                            CCCD = "567890123456",
                            ChuyenNganh = "Khoa Học Máy Tính",
                            DanToc = "Kinh",
                            DiaChi = "112 Đường E, Quận 5, TP.HCM",
                            Email = "hoangvane@sinhvien.com",
                            GioiTinh = "Nam",
                            Khoa = "CNTT",
                            NgayNhapHoc = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(2000, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(581),
                            SoDienThoai = "0905678901",
                            TenSinhVien = "Hoàng Văn E",
                            TinhTrang = "Đang học"
                        },
                        new
                        {
                            MaSinhVien = "SV006",
                            AnhSinhVien = "Image_PK0002.jpeg",
                            CCCD = "678901234567",
                            ChuyenNganh = "Quản Trị Kinh Doanh",
                            DanToc = "Kinh",
                            DiaChi = "123 Đường F, Quận 6, TP.HCM",
                            Email = "dothif@sinhvien.com",
                            GioiTinh = "Nữ",
                            Khoa = "Kinh Tế",
                            NgayNhapHoc = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(2001, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(586),
                            SoDienThoai = "0906789012",
                            TenSinhVien = "Đỗ Thị F",
                            TinhTrang = "Đang học"
                        },
                        new
                        {
                            MaSinhVien = "SV007",
                            AnhSinhVien = "Image_PK0002.jpeg",
                            CCCD = "789012345678",
                            ChuyenNganh = "Mạng Máy Tính",
                            DanToc = "Kinh",
                            DiaChi = "234 Đường G, Quận 7, TP.HCM",
                            Email = "ngovang@sinhvien.com",
                            GioiTinh = "Nam",
                            Khoa = "CNTT",
                            NgayNhapHoc = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(2000, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(589),
                            SoDienThoai = "0907890123",
                            TenSinhVien = "Ngô Văn G",
                            TinhTrang = "Đang học"
                        },
                        new
                        {
                            MaSinhVien = "SV008",
                            AnhSinhVien = "Image_PK0002.jpeg",
                            CCCD = "890123456789",
                            ChuyenNganh = "Kế Toán",
                            DanToc = "Kinh",
                            DiaChi = "345 Đường H, Quận 8, TP.HCM",
                            Email = "phanthih@sinhvien.com",
                            GioiTinh = "Nữ",
                            Khoa = "Kinh Tế",
                            NgayNhapHoc = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(2001, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(592),
                            SoDienThoai = "0908901234",
                            TenSinhVien = "Phan Thị H",
                            TinhTrang = "Đang học"
                        },
                        new
                        {
                            MaSinhVien = "SV009",
                            AnhSinhVien = "Image_PK0002.jpeg",
                            CCCD = "901234567890",
                            ChuyenNganh = "Khoa Học Máy Tính",
                            DanToc = "Kinh",
                            DiaChi = "456 Đường I, Quận 9, TP.HCM",
                            Email = "buivani@sinhvien.com",
                            GioiTinh = "Nam",
                            Khoa = "CNTT",
                            NgayNhapHoc = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(2000, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(597),
                            SoDienThoai = "0909012345",
                            TenSinhVien = "Bùi Văn I",
                            TinhTrang = "Đang học"
                        },
                        new
                        {
                            MaSinhVien = "SV010",
                            AnhSinhVien = "Image_PK0002.jpeg",
                            CCCD = "012345678901",
                            ChuyenNganh = "Quản Trị Kinh Doanh",
                            DanToc = "Kinh",
                            DiaChi = "567 Đường K, Quận 10, TP.HCM",
                            Email = "vothik@sinhvien.com",
                            GioiTinh = "Nữ",
                            Khoa = "Kinh Tế",
                            NgayNhapHoc = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(2001, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThem = new DateTime(2024, 6, 5, 10, 53, 11, 69, DateTimeKind.Local).AddTicks(601),
                            SoDienThoai = "0900123456",
                            TenSinhVien = "Võ Thị K",
                            TinhTrang = "Đang học"
                        });
                });

            modelBuilder.Entity("ApFpoly_API.Model.BangDiem", b =>
                {
                    b.HasOne("ApFpoly_API.Model.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApFpoly_API.Model.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApFpoly_API.Model.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApFpoly_API.Model.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("LopHoc");

                    b.Navigation("MonHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("ApFpoly_API.Model.DiemDanh", b =>
                {
                    b.HasOne("ApFpoly_API.Model.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ApFpoly_API.Model.LichHoc", "LichHoc")
                        .WithMany()
                        .HasForeignKey("MaLichHoc")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ApFpoly_API.Model.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ApFpoly_API.Model.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("LichHoc");

                    b.Navigation("MonHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("ApFpoly_API.Model.LichHoc", b =>
                {
                    b.HasOne("ApFpoly_API.Model.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApFpoly_API.Model.HocKyBlock", "HocKyBlock")
                        .WithMany()
                        .HasForeignKey("MaHocKyBlock")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApFpoly_API.Model.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApFpoly_API.Model.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApFpoly_API.Model.PhongHoc", "PhongHoc")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("HocKyBlock");

                    b.Navigation("LopHoc");

                    b.Navigation("MonHoc");

                    b.Navigation("PhongHoc");
                });

            modelBuilder.Entity("ApFpoly_API.Model.LopHocChiTiet", b =>
                {
                    b.HasOne("ApFpoly_API.Model.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApFpoly_API.Model.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("ApFpoly_API.Model.NopBai", b =>
                {
                    b.HasOne("ApFpoly_API.Model.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApFpoly_API.Model.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApFpoly_API.Model.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApFpoly_API.Model.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("LopHoc");

                    b.Navigation("MonHoc");

                    b.Navigation("SinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
